# Uncomment the next line to define a global platform for your project
 platform :ios, '11.2'

target 'ARphroditeApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ARphroditeApp
	pod 'SwiftProtobuf', '~> 1.0.0'

  target 'ARphroditeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ARphroditeAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
